package util;

public enum  UserError {

    USER_NONE,
    USERNAME_NULL,
    USERNAME_REPEAT,
    NICKNAME_NULL,
    NICKNAME_REPEAT,
    PASSWORD_NULL,
    REPEATPASSWORD_ERROR,
    SUCCESS,
    USERNAME_OR_PASSWORD_ERROR,
    OLDPASSWORD_ERROR,
    NOLOGIN
}
